# This YAML file contains CSI Controller Plugin Sidecars
# external-attacher, external-provisioner, external-snapshotter

kind: Service
apiVersion: v1
metadata:
  name: csi-bizflycloud-controller-service
  namespace: kube-system
  labels:
    app: csi-bizflycloud-controllerplugin
spec:
  selector:
    app: csi-bizflycloud-controllerplugin
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-bizflycloud-controllerplugin
  namespace: kube-system
spec:
  serviceName: "csi-bizflycloud-controller-service"
  replicas: 1
  selector:
    matchLabels:
      app: csi-bizflycloud-controllerplugin
  template:
    metadata:
      labels:
        app: csi-bizflycloud-controllerplugin
    spec:
      serviceAccount: csi-bizflycloud-controller-sa
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.2.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--feature-gates=Topology=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.2.2
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v0.4.0
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: bizflycloud-csi-plugin
          image: cr-hn-1.vccloud.vn/31ff9581861a4d0ea4df5e7dda0f665d/csi-bizflycloud:v0.1.0
          args :
            - /bin/csi-bizflycloud
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cluster=$(CLUSTER_NAME)"
            - "--auth_method=application_credential"
            - "--application_credential_id=$(BIZFLYCLOUD_APPLICATION_CREDENTIAL_ID)"
            - "--application_credential_secret=$(BIZFLYCLOUD_APPLICATION_CREDENTIAL_SECRET)"
            - "--tenant_id=$(TENANT_ID)"
            - "--is_control_plane=true"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLUSTER_NAME
              value: kubernetes
            - name: BIZFLYCLOUD_APPLICATION_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: bizflycloud
                  key: application_credential_id
            - name: BIZFLYCLOUD_APPLICATION_CREDENTIAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: bizflycloud
                  key: application_credential_secret
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: bizflycloud
                  key: tenant_id
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
