apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-hdd-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: premium-hdd
