name: Release to Docker and git
on:
  push:
    tags:
       - v*

jobs:
  docker-block-storage:
    name: Release csi-bizflycloud (Block Storage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: cr-hn-1.bizflycloud.vn/31ff9581861a4d0ea4df5e7dda0f665d/csi-bizflycloud
          username: ${{ secrets.USER_CLOUD }}
          password: ${{ secrets.PASS }}
          tags: "latest,${{ steps.vars.outputs.tag }}"

  docker-file-storage:
    name: Release csi-fs-bizflycloud (File Storage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: cr-hn-1.bizflycloud.vn
          name: cr-hn-1.bizflycloud.vn/31ff9581861a4d0ea4df5e7dda0f665d/csi-fs-bizflycloud
          dockerfile: Dockerfile.fs-bizflycloud
          username: ${{ secrets.USER_CLOUD }}
          password: ${{ secrets.PASS }}
          tags: "latest,${{ steps.vars.outputs.tag }}"
